name: rive_slides
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.6.8
  rive_native:
      path: 'lib/rive_native/'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
